Repository woowa-techcamp-2020/todo-1, pull requests merged in 2020-07, with the labels that each got.

#30 PR: 추가 - Database table 생성 파일
  DB.sql
Labels: DB

#31 PR: 구현 - DataAccessObject
  .env.dev
  .gitignore
  apis/users.js
  app.js
  bin/www
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/constants/poolOptions.js
  dao/constants/table.js
  dao/dao.js
  dao/dto/User.js
  package.json
  routes/index.js
  yarn.lock
Labels: DB

#33 PR: 추가 - 칸반보드 페이지 마크업
  src/app.js
  src/index.html
  src/javascripts/Components/Column.js
  src/javascripts/Components/Element.js
  src/javascripts/Components/Header.js
  src/javascripts/Components/Hover.js
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/Note.js
  src/stylesheets/kanban.css
  src/stylesheets/style.css
Labels: Markup

#35 PR: 리팩토링 - DAO, DTO
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/constants/poolOptions.js
  dao/dao.js
  dao/dto/User.js
  package.json
  utils/datetime.js
  utils/safePromise.js
  yarn.lock
Labels: DB

#37 PR: 추가 - 액티비티 로그
  src/javascripts/Components/ActivityLog.js
  src/javascripts/Components/Header.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/Log.js
  src/stylesheets/activityLog.css
Labels: Javascript, Markup

#42 [#40] fix: 추가 - 마우스 왼쪽 버튼으로만 동작
  src/javascripts/Components/Kanban.js
Labels: Bug

#43 PR: 추가 - 칸반페이지 event handler 버그 수정, 노트이동 기능 추가
  src/javascripts/Components/Column.js
  src/javascripts/Components/Hover.js
  src/javascripts/Components/Kanban.js
  src/stylesheets/kanban.css
Labels: Javascript

#44 PR: 추가 - 칸반 데이터를 가져오는 API
  apis/constants/message.js
  apis/index.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/dto/Column.js
  dao/dto/Kanban.js
  dao/dto/Note.js
  dao/method/getKanbanData.js
Labels: API, DB

#45 PR: 추가 - kanban 페이지 데이터 fetching
  src/javascripts/Components/Column.js
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/Note.js
Labels: API, Markup

#47 PR: 추가 - README.md 초기 파일
  README.md
Labels: docs

#46 PR: 추가 - 모달 및 모달 관리자
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/Modal/DeleteNoteModal.js
  src/javascripts/Components/Modal/EditNoteModal.js
  src/javascripts/Components/Modal/Modal.js
  src/javascripts/Components/Modal/RenameColumnModal.js
  src/javascripts/Components/ModalManager.js
  src/stylesheets/modal.css
Labels: Javascript, Markup

#49 PR: 추가 - 노트 추가 API
  apis/constants/message.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/dto/Note.js
  dao/method/createNote.js
Labels: API

#51 PR: 추가 - 노트 내용 수정 API
  apis/constants/message.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/method/createNote.js
  dao/method/updateNote.js
Labels: API

#52 PR: 추가 - 노트 삭제 API
  apis/constants/message.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/method/deleteNote.js
Labels: API

#55 PR: 추가 - 노트 이동 API
  apis/constants/message.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/DataAccessObject.spec.js
  dao/method/moveNote.js
Labels: API

#54 PR: 구현 - 모달 콜백 함수 및 모달 관리자 전역저장소에 저장
  src/javascripts/Components/Column.js
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/Modal/DeleteNoteModal.js
  src/javascripts/Components/Modal/EditNoteModal.js
  src/javascripts/Components/Modal/Modal.js
  src/javascripts/Components/Modal/RenameColumnModal.js
  src/javascripts/Components/Modal/constants.js
  src/javascripts/Components/ModalManager.js
  src/javascripts/Store/Store.js
  src/stylesheets/kanban.css
  src/stylesheets/modal.css
Labels: Javascript, Markup

#60 PR: HOTFIX - api move note
  apis/kanban.js
  dao/method/getKanbanData.js
  dao/method/moveNote.js
Labels: API, Bug

#57 PR: 추가 - 노트 이동시 API 요청
  src/javascripts/Components/Kanban.js
Labels: Javascript

#61 PR: fix - 노트 이동 버그 수정
  apis/kanban.js
  dao/method/getKanbanData.js
  dao/method/moveNote.js
  src/javascripts/Components/Kanban.js
Labels: API, Bug

#58 PR: 추가 - 노트 수정, 삭제 이벤트 적용
  src/javascripts/Components/Column.js
  src/javascripts/Components/Note.js
Labels: Javascript

#63 PR: !HOTFIX - 빈 컬럼에서 note 생성
  dao/method/createNote.js
Labels: API, Bug, DB

#65 PR: !HOTFIX - 드래그 후 수정된 노트가 화면에 적용 안 되는 버그
  src/javascripts/Components/Column.js
  src/javascripts/Components/Note.js
Labels: Bug

#68 PR: !HOTFIX 노트 이동 dao method
  dao/method/functions/checkCorrectLink.js
  dao/method/functions/pickNoteLink.js
  dao/method/functions/pushNoteToEmptyColumn.js
  dao/method/functions/updateNoteLink.js
  dao/method/moveNote.js
Labels: Bug

#69 PR: feat - 컬럼 제목 수정 API 및 이벤트 연동
  apis/constants/message.js
  apis/constants/rule.js
  apis/kanban.js
  dao/DataAccessObject.js
  dao/method/renameColumn.js
  src/javascripts/Components/Column.js
Labels: API, Javascript

#70 PR: refactor - 객체 프로퍼티와 중복되는 데이터 제거
  src/javascripts/Components/Column.js
  src/javascripts/Components/Kanban.js
Labels: Refactoring

#72 PR: feat - 유저 권한 확인
  src/javascripts/Components/Column.js
  src/javascripts/Store/Store.js
Labels: Javascript, Option

#74 PR: feat - 페이지 라우팅
  app.js
  routes/spa.js
  src/app.js
  src/javascripts/Components/Element.js
  src/javascripts/Components/ErrorPage.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Components/LoginPage.js
  src/javascripts/Components/Router.js
  src/javascripts/Store/Store.js
  src/stylesheets/error.css
Labels: Javascript

#76 PR: feat - 로그인한 유저 정보 연동
  apis/login.js
  src/javascripts/Components/Column.js
  src/javascripts/Components/LoginPage.js
  src/javascripts/Store/Store.js
Labels: API, Javascript

#77 PR: fix - 유저 퍼미션 오류
  src/javascripts/Components/LoginPage.js
  src/javascripts/Store/Store.js
Labels: Bug

#75 PR: 추가 - activity log 적용
  apis/index.js
  apis/kanban.js
  apis/log.js
  dao/DataAccessObject.js
  dao/constants/log.js
  dao/dto/Log.js
  dao/method/createLog.js
  dao/method/readLogs.js
  src/javascripts/Components/ActivityLog.js
  src/javascripts/Components/Column.js
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/Log.js
Labels: API, Javascript

#80 PR: feat - 토큰으로 유저 정보 연동 및 로그인 여부 확인
  apis/constants/config.js
  apis/constants/message.js
  apis/login.js
  dao/dto/UserToken.js
  src/app.js
  src/javascripts/Components/KanbanPage.js
  src/javascripts/Utils/cookie.js
Labels: API, Bug, Javascript

#78 PR: 추가 - 로그에 시간을 계산해 표시
  dao/dto/Log.js
  dao/method/readLogs.js
  src/javascripts/Components/ActivityLog.js
  src/javascripts/Components/Kanban.js
  src/javascripts/Components/Log.js
Labels: Markup

#81 PR: fix - Webpack Entry Point / Plugin SPA 적용
  webpack.config.js
Labels: Bug

#84 PR: HOTFIX - import loginpage 파일 오타 수정
  src/app.js
Labels: Bug

#83 fix: 변경 - schema 구조 update
  DB.sql
Labels: DB

#85 PR: fix - 노트가 많은 경우 scroll
  src/stylesheets/kanban.css
Labels: Markup

#86 PR: fix - 컬럼에 노트가 많을 경우 overflow 속성 변경
  src/stylesheets/kanban.css
Labels: Bug, Markup

#87 PR: 추가 - apidoc
  apis/constants/message.js
  apis/kanban.js
  apis/log.js
Labels: docs

#88 PR: docs - README.md 내용 추가
  README.md
  package.json
Labels: docs
